# Contributors

The following have contributed to the design of the NEON Ecological Forecasting Challenge

## Steering committee

Lead: R. Quinn Thomas (Virginia Tech)\
Program Manager: Jody Peters (University of Notre Dame)

Michael Dietze (Boston University)\
Melissa Kenney (University of Minnesota)\
Jason McLachlan (University of Notre Dame)\
Carl Boettiger (University of California, Berkeley)\
Cayelan Carey (Virginia Tech)\
Leah Johnson (Virginia Tech)\
NEON Representative: Eric Sokol\
Student representatives: Lynda Bradley (Emory)\

Past members of steering committee

Whitney Woelmer (Virginia Tech)\
Alyssa Wilson (University of Notre Dame)\
NEON Representative: Christine Laney\
Jake Weltzin (USGS)\
Andy Fox (UCAR)\

## Theme design

### Aquatics

Freya Olsson, Virginia Tech\
James Guinnip, Kansas State University\
Sarah Burnet, University of Idaho\
Ryan McClure, Virginia Tech\
Chris Brown, National Oceanic and Atmospheric Administration\
Cayelan Carey, Virginia Tech\
Whitney Woelmer, Virginia Tech\
Jake Zwart, United States Geological Survey

### Beetles

Anna Spiers, University of Colorado, Boulder\
Carl Boettiger, University of California, Berkeley\
Tad Dallas, Louisiana State University\
Nico Franz, NEON Biorepository at Arizona State University\
Kari Norman, University of California, Berkeley\
Thilina Surasinghe, Bridgewater State University\
Brett Melbourne, University of Colorado, Boulder\
Eric Sokol, NEON\
Kelsey Yule, NEON Biorepository at Arizona State University

### Phenology

Min Chen, University of Wisconsin, Madison\
Michael Dietze, Boston University\
Kathy Gerst, National Phenology Network\
Chris Jones, NC State University David LeBauer, University of Arizona\
Dabasmita Pal, Michigan State University\
Andrew Richardson, Northern Arizona University\
Arun Ross, Michigan State University\
Bijan Seyednasrollah, Northern Arizona University, PhenoCam Network\
Quinn Thomas, Virginia Tech\
Kathryn Wheeler, Boston University\
Luke Zachmann, Conservation Science Partners\
Kai Zhu, University of California - Santa Cruz

### Terrestrial

George Burba, LI-COR Biosciences\
Jamie Cleverly, Terrestrial Ecosystem Research Network (TERN)\
Ankur Desai, University of Wisconsin, Madison\
Mike Dietze, Boston University\
Andy Fox, Joint Center for Satellite Data Assimilation\
William Hammond, Oklahoma State University\
Danica Lombardozzi, National Center for Atmospheric Research\
Quinn Thomas, Virginia Tech\
Jody Peters, University of Notre Dame\
Alex Young, SUNY - College of Environmental Science & Forestry

### Ticks

Matt Bitters, University of Colorado, Boulder\
Melissa Chen, University of Colorado, Boulder\
John Foster, Boston University\
Leah Johnson, Virginia Tech\
Shannon LaDeau, Cary Institute of Ecosystem Studies\
Cat Lippi, University of Florida\
Brett Melbourne, University of Colorado, Boulder\
Wynne Moss, University of Colorado, Boulder\
Sadie Ryan, University of Florida




