# Participation

## Participation guidance

### How to participate

Participation requires that **one contact person** from each team:

1.  Complete the [registration and model overview](https://nd.qualtrics.com/jfe/form/SV_9MJ29y2xNrBOjqZ){target="_blank"} form for each forecast model you will submit to a particular theme. The registration provides us contact information and information about the modeling approach used to generate the forecast. You will complete the registration for each model you submit to each theme. For example, if you are submitting models to both the phenology and terrestrial daily theme then you will complete the form twice with two different `model_id`'s. If you are submitting two different models to phenology, then you will register twice with two different `model_id`.

    One contact person should register on behalf of their team. That contact person will be asked to provide the group members' names, emails, and affiliations so that everyone in the group can receive an invitation to join the Challenge theme Slack channel and access group resources. In registration, the contact person agrees to the participation agreement below on behalf of the team. You only need to do this once.

2.  Submit forecasts as csv or netCDF file(s)

Teams are allowed and encouraged to join the challenge anytime.

### Teams

Teams can be individuals or groups. They can represent institutions or organizations.

The registration includes team categories (e.g., undergraduate only, graduate only, multi-institution, etc).

Teams can submit forecasts from more than one model. You will register each model with unique `model_id`. Revising a model does not change will change the `model_id` and you will be asked to provide the previous `model_id` so we can link across revisions.

### Slack and GitHub Communication

Once your team is registered, everyone listed will receive an email with an invitation to join the EFI Slack group and the #neon4cast-help channel.

We strongly encourage participants to use the Challenge Slack channel to ask questions, discuss ideas and challenges, and share resources. Overall, we strongly encourage a collegial approach to the Challenge -- this is a friendly competition to move the field forward and bring more people into the community, not a cutthroat competition to win by denying other teams useful information.

### Archiving models

Teams are highly encouraged to publicly archive the code they are using for their forecast models and workflows through GitHub or similar sever. The link to your repository that includes your models would be included on Google Form submission.

## Participation agreement

All participants agree to have their forecast posted in real-time on the NEON Ecological Forecast Challenge [Dashboard](https://projects.ecoforecast.org/neon4cast-dashboard){target="_blank"} and potentially published in a scientific journal. The manuscripts describing the accuracy of forecasts across teams will be coordinated by the Ecological Forecasting Initiative Research Coordination Network and authorship will be extended to members of each team with an opt-in policy.

The license for the forecast output is required to be from the following Creative Commons License options: CC BY, CC BY-SA, CC BY-NC, CC BY-NC-SA. While we recommend a CC BY license, teams may use less permissive CC licenses if more appropriate. The license entry can be the CC option (i.e., CC BY) and a web link to the full CC license (e.g., https://creativecommons.org/licenses/by/4.0/)

If a publication is generated by a forecast team, we ask that the manuscript acknowledge the Ecological Forecasting Initiative Research Coordination Network and its support from the National Science Foundation (DEB-1926388).

## NEON Data Use

NEON data products, software, and derivatives thereof are freely available for use when accompanied by appropriate disclaimers, acknowledgments, and data citations, defined in the [NEON data use policy](https://www.neonscience.org/data/about-data/data-policies){target="_blank"}.

The video below explains how to download and utilize NEON data for the Challenge. The video was recorded for the [2021 Early Career Annual Meeting](https://ecoforecast.org/ecological-forecasting-early-career-annual-meeting/){target="_blank"}

<iframe width="560" height="315" src="https://www.youtube.com/embed/DRDv7axBYGo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

## Additional data options

Individuals and groups may create forecasts that use other publicly available data in addition to the NEON data. Teams are encouraged to make available the code they are using to access, download, and process any additional data constraints they are using, ideally via a Github repo.

As an example of potentially useful external data, each NEON site has subsets of various remote sensing products that are hosted on the ORNL DAAC (ORNL DAAC subsets). These include:

MODIS collection 6: LAI, FPAR, burned area, surface reflectance, land surface temperature, vegetation indices (NDVI, EVI), modeled ET, GPP, NPP.

VIIRS collection 1: surface reflectance, vegetation indices, LAI, FPAR, land surface temperature,

SMAP: modeled NEE, GPP, Rh, SOC

Daymet: daily surface weather data

The video below demonstrates how to access meteorological covariate data for the Challenge. The video was recorded for the [2021 Early Career Annual Meeting](https://ecoforecast.org/ecological-forecasting-early-career-annual-meeting/){target="_blank"}

<iframe width="560" height="315" src="https://www.youtube.com/embed/D1n4q7nrFMw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>
